# Generated by Django 5.2.10 on 2026-01-23 19:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPosterProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('organization_name', models.CharField(blank=True, max_length=128)),
                ('is_business', models.BooleanField(default=False)),
                ('default_location', models.CharField(blank=True, help_text='Typical job location', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical poster profile',
                'verbose_name_plural': 'historical poster profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSeekerProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional hourly rate estimate', max_digits=8, null=True)),
                ('availability_notes', models.CharField(blank=True, max_length=255)),
                ('has_transport', models.BooleanField(default=False)),
                ('willing_to_travel_km', models.PositiveSmallIntegerField(blank=True, help_text='Maximum distance the worker is willing to travel from their base location', null=True)),
                ('id_document', models.TextField(blank=True, max_length=100, null=True)),
                ('id_verified', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical seeker profile',
                'verbose_name_plural': 'historical seeker profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional hourly rate estimate', max_digits=8, null=True)),
                ('availability_notes', models.CharField(blank=True, max_length=255)),
                ('has_transport', models.BooleanField(default=False)),
                ('willing_to_travel_km', models.PositiveSmallIntegerField(blank=True, help_text='Maximum distance the worker is willing to travel from their base location', null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='id_verification/')),
                ('id_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.seekerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
            ],
            options={
                'unique_together': {('seeker', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='seekers', through='profiles.SeekerSkill', to='profiles.skill'),
        ),
        migrations.CreateModel(
            name='PosterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('organization_name', models.CharField(blank=True, max_length=128)),
                ('is_business', models.BooleanField(default=False)),
                ('default_location', models.CharField(blank=True, help_text='Typical job location', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_business'], name='profiles_po_is_busi_9b785b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=models.Index(fields=['hourly_rate'], name='profiles_se_hourly__913f87_idx'),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=models.Index(fields=['is_verified'], name='profiles_se_is_veri_ec7422_idx'),
        ),
    ]
