from datetime import timedelta

from .env import env

AXES_ENABLED = env.bool("AXES_ENABLED")
AXES_FAILURE_LIMIT = env.int("AXES_FAILURE_LIMIT")
AXES_COOLOFF_TIME = timedelta(seconds=env.int("AXES_COOLOFF_TIME"))
AXES_LOCKOUT_PARAMETERS = env.list("AXES_LOCKOUT_PARAMETERS")
AXES_USERNAME_FORM_FIELD = env("AXES_USERNAME_FORM_FIELD")
AXES_IPWARE_META_PRECEDENCE_ORDER = env.list("AXES_IPWARE_META_PRECEDENCE_ORDER")
AXES_CACHE = env("AXES_CACHE")
AXES_HANDLER = env("AXES_HANDLER")
AXES_RESET_ON_SUCCESS = env.bool("AXES_RESET_ON_SUCCESS")
AXES_SENSITIVE_PARAMETERS = env.list("AXES_SENSITIVE_PARAMETERS")
