# Generated by Django 5.2.9 on 2026-01-08 22:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenderDefinitionRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=64, unique=True)),
                ('released_on', models.CharField(max_length=64)),
                ('released_date', models.DateField()),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'defender_definition_release',
            },
        ),
        migrations.CreateModel(
            name='DefenderPlatformUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(db_index=True, max_length=255)),
                ('security_intel_version', models.CharField(max_length=64)),
                ('release_date', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=64)),
                ('engine', models.CharField(max_length=64)),
                ('support_phase', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'defender_platform_update',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDefenderDefinitionRelease',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=64)),
                ('released_on', models.CharField(max_length=64)),
                ('released_date', models.DateField()),
                ('scraped_at', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical defender definition release',
                'verbose_name_plural': 'historical defender definition releases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDefenderPlatformUpdate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('section_title', models.CharField(db_index=True, max_length=255)),
                ('security_intel_version', models.CharField(max_length=64)),
                ('release_date', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=64)),
                ('engine', models.CharField(max_length=64)),
                ('support_phase', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical defender platform update',
                'verbose_name_plural': 'historical defender platform updates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
